override: false

favicon:
  small: /images/natsumi2.3-1.jpg
  medium: /images/natsumi2.3-1.jpg
  apple_touch_icon: /images/natsumi2.3-1.jpg
  safari_pinned_tab: /images/natsumi2.3-1.jpg

footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2019
  # Icon between year and copyright info.
  icon:
    name: fa fa-heart
    animated: false
    color: "#ff0000"
  copyright:
  powered: false
  custom_text: Theme by NexT | Hosted by <a target="_blank" href="https://pages.github.com">GitHub Pages</a>

# Schemes
scheme: Mist
darkmode: false

# Menu
menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  categories: /categories || fa fa-th

# sidebar
sidebar:
  display: post
avatar: 
  url: /images/avatar.png
  rounded: true
social:
  GitHub: https://github.com/tackoil || fab fa-github
  E-Mail: mailto:tackoil@bupt.icu || fa fa-envelope

custom_file_path:
  style: source/_data/styles.styl


reading_progress:
  enable: true
  # Available values: top | bottom
  position: top
  color: "#3EA09E"
  height: 3px


# Front-matter variable (unsupport wrap expand_all).
toc:
  enable: true
  # Automatically add list number to toc.
  number: true
  # If true, all words will placed on next lines if header width longer then sidebar width.
  wrap: false
  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: false
  # Maximum heading depth of generated toc.
  max_depth: 4


# font
font:
  enable: true
  host: https://fonts.loli.net

  global:
    external: true
    family: Noto Serif SC
    size: 16

math:
  per_page: false

  # hexo-renderer-pandoc (or hexo-renderer-kramed) required for full MathJax support.
  mathjax:
    enable: true


codeblock:
  # Code Highlight theme
  # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
  # See: https://github.com/chriskempson/tomorrow-theme
  highlight_theme: normal
  # Add copy button on codeblock
  copy_button:
    enable: true
    # Show text copy result.
    show_result: false
    # Available values: default | flat | mac
    style: flat




